apiVersion: v1
kind: Service
metadata:
  name: atmsimulation-service
  namespace: demo
spec:
  selector:
    app: atmsimulation
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30808
  type: NodePort # to reachable outside of the cluster
